### ISSUE TITLE
interpolate.nim Error: cannot instantiate: 'T'

### ISSUE THREAD

**Issue by HJarausch** [HugoGranstrom/numericalnim#16]
Many thanks for this very interesting package.
I've tried the examples in your documentation.
The following CubicSpline example does not compile on my Nim (devel)

```import math
import numericalnim
var X = @[0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0] # seconds
var Y = @[0.0, 4.0, 6.0, 6.5, 6.4, 6.2, 0.0] # meters/second
let spline = newCubicSpline(X, Y)
echo spline.eval(5.0)
#[
NumNim_BUG.nim(6, 6) template/generic instantiation from here
$HOME/.nimble/pkgs/numericalnim-0.6.0.1/numericalnim/interpolate.nim(182, 27) Error: cannot instantiate: 'T'
]#
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 89a21e4ec71e705833d2aacd069e291cf41a19c6
active boot switches: -d:release

**Comment by HugoGranstrom** [comment]
I'll check it out at once :D

**Comment by HugoGranstrom** [comment]
@HJarausch It's very odd but I can't reproduce it 🤔

**Comment by HugoGranstrom** [comment]
I see that you have version 0.6.0.1 installed, could you try updating to 0.6.1 and see if it solves it?

**Comment by HJarausch** [comment]
Yes, thanks, that solves it.

But strangely   nimble install numericalnim@#master  installs the buggy older version.

**Comment by HugoGranstrom** [comment]
Great that it's solved :D

Yeah that's strange, I usually install `numericalnim@#head` if I want to get the latest commits. Haven't seen `@#master` before.
